import type { LucideIcon } from "lucide-react";
import {
  BadgeAlert,
  BookOpen,
  Box,
  Captions,
  ChartNoAxesCombined,
  CirclePlay,
  Clock3,
  Columns3,
  FileCode2,
  FileInput,
  GalleryHorizontalEnd,
  GalleryThumbnails,
  Github,
  Gitlab,
  Heading,
  Image,
  Languages,
  ListFilter,
  Mail,
  Network,
  Palette,
  PanelTopOpen,
  Pi,
  Quote,
  Sparkles,
  SquareMousePointer,
  Tags,
  TextCursorInput,
  Youtube,
} from "lucide-react";

export type BlowfishTemplate = {
  title: string;
  shortcode: string;
  description: string;
  keywords: string[];
  icon: LucideIcon;
  template: string;
};

const blowfishTemplates: BlowfishTemplate[] = [
  {
    title: "提示框",
    shortcode: "admonition",
    description: "插入 NOTE、TIP、WARNING 等 Markdown 提示块",
    keywords: ["提示", "警告", "注意", "callout", "note", "tip", "warning"],
    icon: BadgeAlert,
    template: "> [!TIP] 自定义标题\n> 在这里填写提示内容。",
  },
  {
    title: "醒目框",
    shortcode: "alert",
    description: "插入带图标和颜色的 Blowfish 消息框",
    keywords: ["警告", "通知", "message", "callout"],
    icon: BadgeAlert,
    template: '{{< alert icon="triangle-exclamation" >}}\n**注意：** 在这里填写醒目内容。\n{{< /alert >}}',
  },
  {
    title: "开篇语",
    shortcode: "lead",
    description: "突出显示文章开头或重要介绍",
    keywords: ["介绍", "开头", "intro"],
    icon: Heading,
    template: "{{< lead >}}\n在这里填写文章开篇语。\n{{< /lead >}}",
  },
  {
    title: "徽章",
    shortcode: "badge",
    description: "插入适合显示状态或元数据的小徽章",
    keywords: ["标签", "状态", "meta"],
    icon: Tags,
    template: "{{< badge >}}\n新内容\n{{< /badge >}}",
  },
  {
    title: "按钮",
    shortcode: "button",
    description: "插入醒目的链接按钮",
    keywords: ["链接", "跳转", "link", "cta"],
    icon: SquareMousePointer,
    template: '{{< button href="https://example.com" target="_blank" >}}\n访问链接\n{{< /button >}}',
  },
  {
    title: "文章卡片",
    shortcode: "article",
    description: "在正文中嵌入站内另一篇文章",
    keywords: ["文章", "内链", "post", "embed"],
    icon: BookOpen,
    template: '{{< article link="/posts/文章路径/" showSummary=true compactSummary=true >}}',
  },
  {
    title: "最近文章列表",
    shortcode: "list",
    description: "按条件显示最近文章或卡片列表",
    keywords: ["列表", "文章", "recent", "posts"],
    icon: ListFilter,
    template: '{{< list title="最近文章" cardView=true limit=6 >}}',
  },
  {
    title: "折叠面板",
    shortcode: "accordion",
    description: "插入可展开和收起的内容分组",
    keywords: ["手风琴", "折叠", "展开", "faq"],
    icon: PanelTopOpen,
    template:
      '{{< accordion mode="collapse" separated=false >}}\n{{< accordionItem title="第一个问题" open=true >}}\n第一个回答。\n{{< /accordionItem >}}\n{{< accordionItem title="第二个问题" >}}\n第二个回答。\n{{< /accordionItem >}}\n{{< /accordion >}}',
  },
  {
    title: "标签页",
    shortcode: "tabs",
    description: "在多个选项卡之间切换内容",
    keywords: ["选项卡", "切换", "tab"],
    icon: Columns3,
    template:
      '{{< tabs group="示例" default="选项一" >}}\n{{< tab label="选项一" icon="check" >}}\n选项一的内容。\n{{< /tab >}}\n{{< tab label="选项二" icon="star" >}}\n选项二的内容。\n{{< /tab >}}\n{{< /tabs >}}',
  },
  {
    title: "时间线",
    shortcode: "timeline",
    description: "展示经历、事件或项目里程碑",
    keywords: ["经历", "事件", "里程碑", "history"],
    icon: Clock3,
    template:
      '{{< timeline >}}\n{{< timelineItem icon="check" header="第一阶段" badge="2026" subheader="阶段说明" md=true >}}\n在这里填写第一阶段内容。\n{{< /timelineItem >}}\n{{< timelineItem icon="star" header="第二阶段" badge="现在" md=true >}}\n在这里填写第二阶段内容。\n{{< /timelineItem >}}\n{{< /timeline >}}',
  },
  {
    title: "关键字组",
    shortcode: "keywordList",
    description: "用带图标的小标签突出技能或关键词",
    keywords: ["技能", "关键词", "标签", "skill"],
    icon: Tags,
    template:
      '{{< keywordList >}}\n{{< keyword icon="github" >}}GitHub{{< /keyword >}}\n{{< keyword icon="code" >}}编程{{< /keyword >}}\n{{< /keywordList >}}',
  },
  {
    title: "图标",
    shortcode: "icon",
    description: "插入 Blowfish 内置 SVG 图标",
    keywords: ["svg", "symbol"],
    icon: Sparkles,
    template: '{{< icon "github" >}}',
  },
  {
    title: "图片 Figure",
    shortcode: "figure",
    description: "插入带说明、链接和缩放支持的图片",
    keywords: ["图片", "照片", "封面", "caption"],
    icon: Image,
    template: '{{< figure src="image.jpg" alt="图片说明" caption="图片标题" >}}',
  },
  {
    title: "排布画册",
    shortcode: "gallery",
    description: "用响应式网格展示多张图片",
    keywords: ["图片", "图库", "相册", "grid"],
    icon: GalleryThumbnails,
    template:
      '{{< gallery >}}\n<img src="gallery/01.jpg" class="grid-w50" />\n<img src="gallery/02.jpg" class="grid-w50" />\n{{< /gallery >}}',
  },
  {
    title: "滑动画册",
    shortcode: "carousel",
    description: "用轮播方式展示多张图片",
    keywords: ["图片", "轮播", "相册", "slider"],
    icon: GalleryHorizontalEnd,
    template: '{{< carousel images="{gallery/01.jpg,gallery/02.jpg}" aspectRatio="16-9" interval="2500" >}}',
  },
  {
    title: "截图",
    shortcode: "screenshot",
    description: "以设备像素比例显示页面资源截图",
    keywords: ["图片", "屏幕", "screen"],
    icon: Captions,
    template: '{{< screenshot src="screenshot.png" alt="截图说明" caption="截图标题" >}}',
  },
  {
    title: "Mermaid 图表",
    shortcode: "mermaid",
    description: "用文本绘制流程图、时序图或思维导图",
    keywords: ["流程图", "思维导图", "diagram", "flowchart"],
    icon: Network,
    template: "{{< mermaid >}}\ngraph LR;\nA[开始] --> B[完成];\n{{< /mermaid >}}",
  },
  {
    title: "Chart.js 图表",
    shortcode: "chart",
    description: "插入柱状图、折线图等数据图表",
    keywords: ["数据", "柱状图", "折线图", "graph"],
    icon: ChartNoAxesCombined,
    template:
      "{{< chart >}}\ntype: 'bar',\ndata: {\n  labels: ['A', 'B', 'C'],\n  datasets: [{ label: '数量', data: [12, 19, 8] }]\n}\n{{< /chart >}}",
  },
  {
    title: "KaTeX 数学公式",
    shortcode: "katex",
    description: "启用当前文章的数学公式渲染",
    keywords: ["数学", "公式", "latex", "math"],
    icon: Pi,
    template: "{{< katex >}}\n\n$$\nf(x) = x^2 + 2x + 1\n$$",
  },
  {
    title: "色板",
    shortcode: "swatches",
    description: "并排预览最多三种颜色",
    keywords: ["颜色", "调色板", "color"],
    icon: Palette,
    template: '{{< swatches "#64748b" "#3b82f6" "#06b6d4" >}}',
  },
  {
    title: "GitHub 仓库卡片",
    shortcode: "github",
    description: "显示 GitHub 仓库信息、Star 和 Fork",
    keywords: ["代码", "仓库", "repo", "card"],
    icon: Github,
    template: '{{< github repo="ZhangDaLi-666/my_blog" showThumbnail=true >}}',
  },
  {
    title: "GitHub Gist",
    shortcode: "gist",
    description: "嵌入整个 Gist 或其中一个文件",
    keywords: ["代码", "片段", "snippet"],
    icon: FileCode2,
    template: '{{< gist "用户名" "GIST_ID" >}}',
  },
  {
    title: "GitLab 项目卡片",
    shortcode: "gitlab",
    description: "显示 GitLab 项目的实时信息",
    keywords: ["代码", "仓库", "repo", "card"],
    icon: Gitlab,
    template: '{{< gitlab projectID="278964" >}}',
  },
  {
    title: "Codeberg 仓库卡片",
    shortcode: "codeberg",
    description: "显示 Codeberg 仓库的实时信息",
    keywords: ["代码", "仓库", "repo", "card"],
    icon: Box,
    template: '{{< codeberg repo="forgejo/forgejo" >}}',
  },
  {
    title: "Gitea 仓库卡片",
    shortcode: "gitea",
    description: "显示 Gitea 实例中的仓库信息",
    keywords: ["代码", "仓库", "repo", "card"],
    icon: Box,
    template: '{{< gitea server="https://gitea.com" repo="用户名/仓库" >}}',
  },
  {
    title: "Forgejo 仓库卡片",
    shortcode: "forgejo",
    description: "显示 Forgejo 实例中的仓库信息",
    keywords: ["代码", "仓库", "repo", "card"],
    icon: Box,
    template: '{{< forgejo server="https://codeberg.org" repo="用户名/仓库" >}}',
  },
  {
    title: "Hugging Face 卡片",
    shortcode: "huggingface",
    description: "显示 Hugging Face 模型或数据集信息",
    keywords: ["模型", "数据集", "ai", "model", "dataset"],
    icon: Box,
    template: '{{< huggingface model="google-bert/bert-base-uncased" >}}',
  },
  {
    title: "Ansible Galaxy 卡片",
    shortcode: "ansible",
    description: "显示 Ansible Role 或 Collection 信息",
    keywords: ["自动化", "role", "collection"],
    icon: Box,
    template: '{{< ansible collection="namespace.collection" >}}',
  },
  {
    title: "代码导入",
    shortcode: "codeimporter",
    description: "从远程文件导入指定行的源代码",
    keywords: ["远程", "源码", "import", "source"],
    icon: FileInput,
    template: '{{< codeimporter url="https://example.com/example.js" type="javascript" startLine="1" endLine="20" >}}',
  },
  {
    title: "Markdown 导入",
    shortcode: "mdimporter",
    description: "从远程地址导入 Markdown 内容",
    keywords: ["远程", "文档", "import"],
    icon: FileInput,
    template: '{{< mdimporter url="https://example.com/README.md" >}}',
  },
  {
    title: "打字机效果",
    shortcode: "typeit",
    description: "逐字显示一行或多行文字",
    keywords: ["动画", "文字", "typing", "animation"],
    icon: TextCursorInput,
    template:
      "{{< typeit tag=h3 speed=75 breakLines=false loop=true >}}\n第一句话\n第二句话\n{{< /typeit >}}",
  },
  {
    title: "视频播放器",
    shortcode: "video",
    description: "嵌入本地或远程视频，可设置封面和说明",
    keywords: ["媒体", "mp4", "player"],
    icon: CirclePlay,
    template: '{{< video src="video.mp4" poster="poster.jpg" caption="视频说明" controls=true playsinline=true >}}',
  },
  {
    title: "YouTube Lite",
    shortcode: "youtubeLite",
    description: "使用 Blowfish 轻量播放器嵌入 YouTube",
    keywords: ["视频", "播放器", "youtube"],
    icon: Youtube,
    template: '{{< youtubeLite id="VIDEO_ID" label="视频标题" >}}',
  },
  {
    title: "YouTube",
    shortcode: "youtube",
    description: "使用 Hugo 内置简码嵌入 YouTube",
    keywords: ["视频", "播放器", "hugo"],
    icon: Youtube,
    template: "{{< youtube VIDEO_ID >}}",
  },
  {
    title: "Vimeo",
    shortcode: "vimeo_simple",
    description: "使用 Hugo 隐私友好简码嵌入 Vimeo",
    keywords: ["视频", "播放器", "hugo"],
    icon: CirclePlay,
    template: "{{< vimeo_simple VIDEO_ID >}}",
  },
  {
    title: "X / Twitter",
    shortcode: "twitter_simple",
    description: "使用 Hugo 隐私友好简码嵌入帖子",
    keywords: ["推文", "社交", "tweet", "x"],
    icon: Quote,
    template: '{{< twitter_simple user="用户名" id="POST_ID" >}}',
  },
  {
    title: "邮箱链接",
    shortcode: "email",
    description: "插入经过简单保护的邮箱链接",
    keywords: ["邮件", "联系", "mailto"],
    icon: Mail,
    template: '{{< email email="name@example.com" subject="邮件主题" text="联系我" >}}',
  },
  {
    title: "从右向左文本",
    shortcode: "rtl",
    description: "插入阿拉伯语等从右向左书写的内容",
    keywords: ["方向", "语言", "arabic", "direction"],
    icon: Languages,
    template: "{{% rtl %}}\n在这里填写从右向左的内容。\n{{% /rtl %}}",
  },
  {
    title: "从左向右文本",
    shortcode: "ltr",
    description: "在 RTL 内容中插入从左向右书写的片段",
    keywords: ["方向", "语言", "direction"],
    icon: Languages,
    template: "{{% ltr %}}\n在这里填写从左向右的内容。\n{{% /ltr %}}",
  },
];

export default blowfishTemplates;
